// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nbiquffvrdjoxionykkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iaXF1ZmZ2cmRqb3hpb255a2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzMyOTQsImV4cCI6MjA3MjMwOTI5NH0.uGnMD9WurT1mud6tY8lnHLqk4lTH_6k0ZSvBjg2SBzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);